'use client';

/**
 * Faz Live Preview Component
 * 
 * Uses StackBlitz SDK to create an actual running Next.js preview
 * of the generated code files in an embedded environment.
 */

import React, { useEffect, useRef, useState, useCallback } from 'react';
import { Loader2, ExternalLink, RefreshCw, AlertCircle } from 'lucide-react';
import sdk from '@stackblitz/sdk';
import type { FazFile } from '@/types/faz';

interface FazLivePreviewProps {
  files: FazFile[];
  projectName: string;
  previewMode: 'desktop' | 'tablet' | 'mobile';
  className?: string;
}

// Base Next.js template files
const getBaseFiles = (projectName: string): Record<string, string> => ({
  'package.json': JSON.stringify({
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start'
    },
    dependencies: {
      'next': '14.2.0',
      'react': '^18.3.0',
      'react-dom': '^18.3.0'
    },
    devDependencies: {
      '@types/node': '^20',
      '@types/react': '^18',
      'typescript': '^5'
    }
  }, null, 2),
  
  'next.config.mjs': `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;`,

  'tailwind.config.js': `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`,

  'postcss.config.js': `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`,

  'tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'es5',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: {
        '@/*': ['./*']
      }
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules']
  }, null, 2),
});

export function FazLivePreview({ 
  files, 
  projectName, 
  // previewMode is available for future responsive adjustments
  previewMode: _previewMode,
  className = ''
}: FazLivePreviewProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  // vmInstance kept for potential future VM interactions (file updates, etc.)
  const [, setVmInstance] = useState<unknown | null>(null);
  
  // Suppress unused variable lint - previewMode available for future responsive features
  void _previewMode;
  
  // Convert FazFiles to StackBlitz file format
  const convertFilesToStackBlitz = useCallback((): Record<string, string> => {
    const baseFiles = getBaseFiles(projectName);
    const projectFiles: Record<string, string> = {};
    
    files.forEach(file => {
      // Normalize path - remove leading slashes
      let path = file.path.replace(/^\/+/, '');
      
      // Convert 'src/app/...' to 'app/...' for Next.js 14 app router
      if (path.startsWith('src/')) {
        path = path.replace('src/', '');
      }
      
      projectFiles[path] = file.content;
    });
    
    // Ensure we have a globals.css
    if (!projectFiles['app/globals.css']) {
      projectFiles['app/globals.css'] = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}`;
    }
    
    // Ensure we have a layout.tsx
    if (!projectFiles['app/layout.tsx']) {
      projectFiles['app/layout.tsx'] = `import './globals.css'

export const metadata = {
  title: '${projectName}',
  description: 'Generated by Faz Code',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`;
    }
    
    // Ensure we have a page.tsx
    if (!projectFiles['app/page.tsx']) {
      projectFiles['app/page.tsx'] = `export default function Home() {
  return (
    <main className="min-h-screen p-8 bg-slate-950 text-white">
      <h1 className="text-4xl font-bold text-purple-400">${projectName}</h1>
      <p className="text-slate-400 mt-4">Run the pipeline to generate your app</p>
    </main>
  )
}`;
    }
    
    return { ...baseFiles, ...projectFiles };
  }, [files, projectName]);
  
  const initializePreview = useCallback(async () => {
    if (!containerRef.current || files.length === 0) return;
    
    setLoading(true);
    setError(null);
    
    try {
      const stackblitzFiles = convertFilesToStackBlitz();
      
      // Embed StackBlitz project
      const vm = await sdk.embedProject(
        containerRef.current,
        {
          title: projectName,
          description: 'Generated by Faz Code',
          template: 'node',
          files: stackblitzFiles,
        },
        {
          openFile: 'app/page.tsx',
          view: 'preview',
          hideExplorer: true,
          hideNavigation: true,
          hideDevTools: true,
          theme: 'dark',
          startScript: 'dev',
          height: '100%',
        }
      );
      
      setVmInstance(vm);
      setLoading(false);
    } catch (err) {
      console.error('[FazPreview] Failed to initialize:', err);
      setError(err instanceof Error ? err.message : 'Failed to initialize preview');
      setLoading(false);
    }
  }, [files, projectName, convertFilesToStackBlitz]);
  
  // Initialize on mount and when files change
  useEffect(() => {
    if (files.length > 0) {
      initializePreview();
    }
  }, [initializePreview, files.length]);
  
  // Refresh handler
  const handleRefresh = () => {
    initializePreview();
  };
  
  // Show placeholder when no files
  if (files.length === 0) {
    return (
      <div className={`flex items-center justify-center h-full bg-[#0a0a0f] ${className}`}>
        <div className="text-center text-[#64748B]">
          <Loader2 size={32} className="mx-auto mb-4 opacity-40 animate-pulse" />
          <p className="text-sm">Waiting for generated files...</p>
          <p className="text-xs mt-2 opacity-60">Run the pipeline to see your app</p>
        </div>
      </div>
    );
  }
  
  return (
    <div className={`relative h-full w-full ${className}`}>
      {/* Control bar */}
      <div className="absolute top-0 left-0 right-0 z-10 flex items-center justify-between px-3 py-1.5 bg-gradient-to-r from-purple-600/90 to-indigo-600/90 backdrop-blur-sm">
        <span className="text-[10px] text-white/90 font-medium">
          ⚡ Live Preview - {files.length} files
        </span>
        <div className="flex items-center gap-2">
          <button
            onClick={handleRefresh}
            className="p-1 text-white/70 hover:text-white transition-colors"
            title="Refresh preview"
          >
            <RefreshCw size={12} />
          </button>
          <button
            onClick={() => window.open('https://stackblitz.com', '_blank')}
            className="p-1 text-white/70 hover:text-white transition-colors"
            title="Open in StackBlitz"
          >
            <ExternalLink size={12} />
          </button>
        </div>
      </div>
      
      {/* Loading state */}
      {loading && (
        <div className="absolute inset-0 flex items-center justify-center bg-[#0a0a0f] z-20">
          <div className="text-center">
            <Loader2 size={32} className="mx-auto mb-4 text-purple-500 animate-spin" />
            <p className="text-sm text-[#94A3B8]">Starting preview server...</p>
            <p className="text-xs text-[#64748B] mt-2">This may take a few seconds</p>
          </div>
        </div>
      )}
      
      {/* Error state */}
      {error && !loading && (
        <div className="absolute inset-0 flex items-center justify-center bg-[#0a0a0f] z-20">
          <div className="text-center max-w-md px-6">
            <AlertCircle size={32} className="mx-auto mb-4 text-red-500" />
            <p className="text-sm text-red-400 mb-2">Preview failed to load</p>
            <p className="text-xs text-[#64748B] mb-4">{error}</p>
            <button
              onClick={handleRefresh}
              className="px-4 py-2 text-xs bg-purple-600/20 text-purple-400 rounded-lg hover:bg-purple-600/30 transition-colors"
            >
              Try Again
            </button>
          </div>
        </div>
      )}
      
      {/* StackBlitz container */}
      <div 
        ref={containerRef} 
        className="w-full h-full pt-8"
        style={{ 
          opacity: loading || error ? 0 : 1,
          transition: 'opacity 0.3s ease'
        }}
      />
    </div>
  );
}

