"""
Memory Tag models for flexible categorization system.

Tags provide additional categorization beyond memory_type,
allowing for flexible organization and filtering.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime
from uuid import UUID


TagType = Literal[
    'system',     # Predefined system tags (available to all)
    'custom',     # User-created tags
    'auto',       # Auto-generated by Nicole
    'emotion',    # Emotional context tags
    'temporal'    # Time-based tags
]

AssignedBy = Literal['user', 'nicole', 'system']


class MemoryTagCreate(BaseModel):
    """Create a new tag."""
    name: str = Field(..., min_length=1, max_length=50)
    description: Optional[str] = Field(None, max_length=200)
    color: str = Field(default='#9CA3AF', pattern=r'^#[0-9A-Fa-f]{6}$')
    icon: Optional[str] = Field(None, max_length=10)
    tag_type: TagType = 'custom'


class MemoryTagUpdate(BaseModel):
    """Update an existing tag."""
    name: Optional[str] = Field(None, min_length=1, max_length=50)
    description: Optional[str] = Field(None, max_length=200)
    color: Optional[str] = Field(None, pattern=r'^#[0-9A-Fa-f]{6}$')
    icon: Optional[str] = Field(None, max_length=10)


class MemoryTag(BaseModel):
    """Full memory tag model."""
    id: UUID
    user_id: Optional[UUID]  # NULL for system tags
    name: str
    description: Optional[str]
    color: str
    icon: Optional[str]
    tag_type: TagType
    usage_count: int
    created_at: datetime
    
    class Config:
        from_attributes = True


class TagAssignment(BaseModel):
    """Assignment of a tag to a memory."""
    id: UUID
    memory_id: UUID
    tag_id: UUID
    assigned_at: datetime
    assigned_by: AssignedBy
    
    # Expanded fields
    tag: Optional[MemoryTag] = None
    
    class Config:
        from_attributes = True


class TagAssignmentCreate(BaseModel):
    """Assign a tag to a memory."""
    tag_id: UUID
    assigned_by: AssignedBy = 'user'


class BulkTagAssignment(BaseModel):
    """Bulk assign tags to a memory."""
    tag_ids: List[UUID]
    assigned_by: AssignedBy = 'user'

